import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'es' | 'en' | 'pt';

interface LanguageContextProps {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'es',
  setLanguage: () => {},
  t: (key: string) => key,
});

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  es: {
    system: {
      title: 'Sistema de Validaciones',
      subtitle: 'Control de Calidad',
    },
    menu: {
      dashboard: 'Dashboard',
      products: 'Productos',
      validations: 'Validaciones',
      equipments: 'Equipos',
      users: 'Usuarios',
      security: 'Seguridad',
      settings: 'Configuración',
      reports: 'Reportes',
    },
    login: {
      title: 'Acceso al Sistema',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      button: 'Iniciar Sesión',
      loading: 'Iniciando Sesión...',
      success: 'Inicio de Sesión Exitoso',
      welcome: 'Bienvenido al Sistema de Validaciones',
      error: 'Error de Autenticación',
      logout: 'Cerrar Sesión',
      logoutSuccess: 'Sesión cerrada correctamente.',
    },
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      edit: 'Editar',
      delete: 'Eliminar',
      upload: 'Subir',
      download: 'Descargar',
      view: 'Ver',
      print: 'Imprimir',
    },
    stats: {
      validated: 'Validadas',
      expiring: 'Próximas a Vencer',
      expired: 'Vencidas',
    },
    validations: {
      subtitle: 'Gestión de validaciones de productos y materias primas',
      new: 'Nueva Validación',
      list: 'Lista de Validaciones',
      manage: 'Gestionar validaciones',
      search: 'Buscar validaciones...',
      no_results: 'No se encontraron resultados',
      no_validations: 'No hay validaciones registradas',
      validation_code: 'Código de Validación',
      product_raw_material: 'Producto / Materia Prima',
      product_raw_material_code: 'Código',
      validation_type: 'Tipo de Validación',
      subcategory: 'Subcategoría',
      equipment: 'Equipo',
      status: 'Estado',
      expiry_date: 'Fecha de Expiración',
      actions: 'Acciones',
      completed: 'Validaciones completadas',
      next30days: 'Validaciones que vencen en los próximos 30 días',
      immediate: 'Validaciones vencidas que requieren atención inmediata',
      protocols: 'Protocolos',
      withDocumentation: 'Validaciones con documentación adjunta',
      manufacturing: 'Fabricación',
      packaging: 'Empaque',
      assay: 'Valoración',
      dissolution: 'Disolución',
      impurities: 'Impurezas',
      uniformity: 'Uniformidad de Unidades de Dosificación',
      identification: 'Identificación',
      traces: 'Trazas',
      not_applicable: 'No Aplica',
      add_product_raw_material: 'Agregar Validación',
    },
    products: {
      title: 'Productos',
      subtitle: 'Gestión de productos y materias primas',
      add_product: 'Agregar Producto',
      created: 'Producto Creado',
      product: 'Producto',
      added_successfully: 'agregado exitosamente',
      finished_products: 'Productos Terminados',
      raw_materials: 'Materias Primas',
      packaging_materials: 'Materiales de Empaque',
      increase_last_month: 'Incremento del mes pasado',
      product_list: 'Lista de Productos',
      registered_products: 'Productos registrados en el sistema',
      module_in_development: 'Módulo en desarrollo',
      add_new_product: 'Agregar Nuevo Producto',
      product_code: 'Código de Producto',
      product_name: 'Nombre de Producto',
      product_type: 'Tipo de Producto',
      select_type: 'Seleccionar Tipo',
      finished_product: 'Producto Terminado',
      raw_material: 'Materia Prima',
      packaging_material: 'Material de Empaque',
      description: 'Descripción',
      product_description: 'Descripción del producto',
    },
    security: {
      title: 'Seguridad',
      subtitle: 'Configuración de seguridad y permisos del sistema',
      settings: 'Configuración de Seguridad',
      settings_desc: 'Configura las políticas de seguridad',
      permissions: 'Permisos del Sistema',
      permissions_desc: 'Administra los permisos de usuario',
      audit_log: 'Registro de Auditoría',
      audit_log_desc: 'Historial de actividades del sistema',
      two_factor: 'Autenticación de Dos Factores',
      two_factor_desc: 'Añade una capa extra de seguridad',
      password_expiry: 'Expiración de Contraseña (días)',
      session_timeout: 'Tiempo de Sesión (minutos)',
      login_attempts: 'Intentos de Login Máximos',
      audit_logging: 'Registro de Auditoría',
      audit_logging_desc: 'Registrar todas las actividades',
      encryption: 'Cifrado de Datos',
      encryption_desc: 'Cifrar datos sensibles',
      access_restricted: 'Acceso Restringido',
      no_permissions: 'No tienes permisos para acceder a este módulo',
      new_user: 'Nuevo Usuario',
      add_new_user: 'Agregar Nuevo Usuario',
      full_name: 'Nombre Completo',
      enter_name: 'Ingrese el nombre completo',
      email: 'Correo Electrónico',
      enter_email: 'Ingrese el correo electrónico',
      role: 'Rol',
      password: 'Contraseña',
      enter_password: 'Ingrese la contraseña',
      user_created: 'Usuario Creado',
      user: 'Usuario',
      created_successfully: 'creado exitosamente',
      permission_updated: 'Permiso Actualizado',
      permission_updated_desc: 'El permiso ha sido actualizado',
      setting_updated: 'Configuración Actualizada',
      setting_updated_desc: 'La configuración ha sido actualizada',
      date_time: 'Fecha y Hora',
      user: 'Usuario',
      action: 'Acción',
      resource: 'Recurso',
      status: 'Estado',
      ip_address: 'Dirección IP',
    },
    permissions: {
      create_validations: 'Crear Validaciones',
      create_validations_desc: 'Crear nuevas validaciones',
      edit_validations: 'Editar Validaciones',
      edit_validations_desc: 'Editar validaciones existentes',
      manage_users: 'Gestionar Usuarios',
      manage_users_desc: 'Gestionar usuarios del sistema',
      export_reports: 'Exportar Reportes',
      export_reports_desc: 'Exportar reportes del sistema',
    },
    roles: {
      administrator: 'Administrador',
      coordinator: 'Coordinador',
      analyst: 'Analista',
      viewer: 'Visualizador',
    },
    status: {
      success: 'Éxito',
      failed: 'Falló',
      warning: 'Advertencia',
      validado: 'Validado',
      proximo: 'Próximo a Vencer',
      vencido: 'Vencido',
      revalidacion: 'En Revalidación',
      en_validacion: 'En Validación',
      por_revalidar: 'Por Revalidar',
      primera_revision: 'Primera Revisión',
      segunda_revision: 'Segunda Revisión',
    },
  },
  en: {
    system: {
      title: 'Validations System',
      subtitle: 'Quality Control',
    },
    menu: {
      dashboard: 'Dashboard',
      products: 'Products',
      validations: 'Validations',
      equipments: 'Equipments',
      users: 'Users',
      security: 'Security',
      settings: 'Settings',
      reports: 'Reports',
    },
    login: {
      title: 'System Access',
      email: 'Email',
      password: 'Password',
      button: 'Sign In',
      loading: 'Signing In...',
      success: 'Successful Login',
      welcome: 'Welcome to the Validations System',
      error: 'Authentication Error',
      logout: 'Logout',
      logoutSuccess: 'Logged out successfully.',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      upload: 'Upload',
      download: 'Download',
      view: 'View',
      print: 'Print',
    },
    stats: {
      validated: 'Validated',
      expiring: 'Expiring Soon',
      expired: 'Expired',
    },
    validations: {
      subtitle: 'Management of product and raw material validations',
      new: 'New Validation',
      list: 'Validations List',
      manage: 'Manage validations',
      search: 'Search validations...',
      no_results: 'No results found',
      no_validations: 'No validations registered',
      validation_code: 'Validation Code',
      product_raw_material: 'Product / Raw Material',
      product_raw_material_code: 'Code',
      validation_type: 'Validation Type',
      subcategory: 'Subcategory',
      equipment: 'Equipment',
      status: 'Status',
      expiry_date: 'Expiry Date',
      actions: 'Actions',
      completed: 'Completed validations',
      next30days: 'Validations expiring in the next 30 days',
      immediate: 'Expired validations requiring immediate attention',
      protocols: 'Protocols',
      withDocumentation: 'Validations with attached documentation',
      manufacturing: 'Manufacturing',
      packaging: 'Packaging',
      assay: 'Assay',
      dissolution: 'Dissolution',
      impurities: 'Impurities',
      uniformity: 'Uniformity of Dosage Units',
      identification: 'Identification',
      traces: 'Traces',
      not_applicable: 'Not Applicable',
      add_product_raw_material: 'Add Validation',
    },
    products: {
      title: 'Products',
      subtitle: 'Management of products and raw materials',
      add_product: 'Add Product',
      created: 'Product Created',
      product: 'Product',
      added_successfully: 'added successfully',
      finished_products: 'Finished Products',
      raw_materials: 'Raw Materials',
      packaging_materials: 'Packaging Materials',
      increase_last_month: 'Increase last month',
      product_list: 'Product List',
      registered_products: 'Products registered in the system',
      module_in_development: 'Module in development',
      add_new_product: 'Add New Product',
      product_code: 'Product Code',
      product_name: 'Product Name',
      product_type: 'Product Type',
      select_type: 'Select Type',
      finished_product: 'Finished Product',
      raw_material: 'Raw Material',
      packaging_material: 'Packaging Material',
      description: 'Description',
      product_description: 'Product description',
    },
    security: {
      title: 'Security',
      subtitle: 'System security configuration and permissions',
      settings: 'Security Settings',
      settings_desc: 'Configure security policies',
      permissions: 'System Permissions',
      permissions_desc: 'Manage user permissions',
      audit_log: 'Audit Log',
      audit_log_desc: 'System activity history',
      two_factor: 'Two-Factor Authentication',
      two_factor_desc: 'Add an extra layer of security',
      password_expiry: 'Password Expiry (days)',
      session_timeout: 'Session Timeout (minutes)',
      login_attempts: 'Maximum Login Attempts',
      audit_logging: 'Audit Logging',
      audit_logging_desc: 'Log all activities',
      encryption: 'Data Encryption',
      encryption_desc: 'Encrypt sensitive data',
      access_restricted: 'Access Restricted',
      no_permissions: 'You do not have permissions to access this module',
      new_user: 'New User',
      add_new_user: 'Add New User',
      full_name: 'Full Name',
      enter_name: 'Enter full name',
      email: 'Email',
      enter_email: 'Enter email address',
      role: 'Role',
      password: 'Password',
      enter_password: 'Enter password',
      user_created: 'User Created',
      user: 'User',
      created_successfully: 'created successfully',
      permission_updated: 'Permission Updated',
      permission_updated_desc: 'Permission has been updated',
      setting_updated: 'Setting Updated',
      setting_updated_desc: 'Setting has been updated',
      date_time: 'Date and Time',
      action: 'Action',
      resource: 'Resource',
      status: 'Status',
      ip_address: 'IP Address',
    },
    permissions: {
      create_validations: 'Create Validations',
      create_validations_desc: 'Create new validations',
      edit_validations: 'Edit Validations',
      edit_validations_desc: 'Edit existing validations',
      manage_users: 'Manage Users',
      manage_users_desc: 'Manage system users',
      export_reports: 'Export Reports',
      export_reports_desc: 'Export system reports',
    },
    roles: {
      administrator: 'Administrator',
      coordinator: 'Coordinator',
      analyst: 'Analyst',
      viewer: 'Viewer',
    },
    status: {
      success: 'Success',
      failed: 'Failed',
      warning: 'Warning',
      validado: 'Validated',
      proximo: 'Expiring Soon',
      vencido: 'Expired',
      revalidacion: 'In Revalidation',
      en_validacion: 'In Validation',
      por_revalidar: 'To Revalidate',
      primera_revision: 'First Review',
      segunda_revision: 'Second Review',
    },
  },
  pt: {
    system: {
      title: 'Sistema de Validações',
      subtitle: 'Controle de Qualidade',
    },
    menu: {
      dashboard: 'Painel',
      products: 'Produtos',
      validations: 'Validações',
      equipments: 'Equipamentos',
      users: 'Usuários',
      security: 'Segurança',
      settings: 'Configurações',
      reports: 'Relatórios',
    },
    login: {
      title: 'Acesso ao Sistema',
      email: 'Email',
      password: 'Senha',
      button: 'Entrar',
      loading: 'Entrando...',
      success: 'Login Bem-Sucedido',
      welcome: 'Bem-vindo ao Sistema de Validações',
      error: 'Erro de Autenticação',
      logout: 'Sair',
      logoutSuccess: 'Saiu com sucesso.',
    },
    common: {
      save: 'Salvar',
      cancel: 'Cancelar',
      edit: 'Editar',
      delete: 'Excluir',
      upload: 'Enviar',
      download: 'Baixar',
      view: 'Visualizar',
      print: 'Imprimir',
    },
    stats: {
      validated: 'Validadas',
      expiring: 'Próximas ao Vencimento',
      expired: 'Vencidas',
    },
    validations: {
      subtitle: 'Gestão de validações de produtos e matérias-primas',
      new: 'Nova Validação',
      list: 'Lista de Validações',
      manage: 'Gerenciar validações',
      search: 'Pesquisar validações...',
      no_results: 'Nenhum resultado encontrado',
      no_validations: 'Nenhuma validação registrada',
      validation_code: 'Código de Validação',
      product_raw_material: 'Produto / Matéria-Prima',
      product_raw_material_code: 'Código',
      validation_type: 'Tipo de Validação',
      subcategory: 'Subcategoria',
      equipment: 'Equipamento',
      status: 'Status',
      expiry_date: 'Data de Expiração',
      actions: 'Ações',
      completed: 'Validações concluídas',
      next30days: 'Validações que expiram nos próximos 30 dias',
      immediate: 'Validações expiradas que requerem atenção imediata',
      protocols: 'Protocolos',
      withDocumentation: 'Validações com documentação anexada',
      manufacturing: 'Fabricação',
      packaging: 'Embalagem',
      assay: 'Ensaio',
      dissolution: 'Dissolução',
      impurities: 'Impurezas',
      uniformity: 'Uniformidade de Unidades de Dosagem',
      identification: 'Identificação',
      traces: 'Traços',
      not_applicable: 'Não Aplicável',
      add_product_raw_material: 'Adicionar Validação',
    },
    products: {
      title: 'Produtos',
      subtitle: 'Gestão de produtos e matérias-primas',
      add_product: 'Adicionar Produto',
      created: 'Produto Criado',
      product: 'Produto',
      added_successfully: 'adicionado com sucesso',
      finished_products: 'Produtos Acabados',
      raw_materials: 'Matérias-Primas',
      packaging_materials: 'Materiais de Embalagem',
      increase_last_month: 'Aumento no mês passado',
      product_list: 'Lista de Produtos',
      registered_products: 'Produtos registrados no sistema',
      module_in_development: 'Módulo em desenvolvimento',
      add_new_product: 'Adicionar Novo Produto',
      product_code: 'Código do Produto',
      product_name: 'Nome do Produto',
      product_type: 'Tipo de Produto',
      select_type: 'Selecionar Tipo',
      finished_product: 'Produto Acabado',
      raw_material: 'Matéria-Prima',
      packaging_material: 'Material de Embalagem',
      description: 'Descrição',
      product_description: 'Descrição do produto',
    },
    security: {
      title: 'Segurança',
      subtitle: 'Configuração de segurança e permissões do sistema',
      settings: 'Configurações de Segurança',
      settings_desc: 'Configure políticas de segurança',
      permissions: 'Permissões do Sistema',
      permissions_desc: 'Gerenciar permissões de usuário',
      audit_log: 'Log de Auditoria',
      audit_log_desc: 'Histórico de atividades do sistema',
      two_factor: 'Autenticação de Dois Fatores',
      two_factor_desc: 'Adicione uma camada extra de segurança',
      password_expiry: 'Expiração de Senha (dias)',
      session_timeout: 'Timeout de Sessão (minutos)',
      login_attempts: 'Tentativas Máximas de Login',
      audit_logging: 'Log de Auditoria',
      audit_logging_desc: 'Registrar todas as atividades',
      encryption: 'Criptografia de Dados',
      encryption_desc: 'Criptografar dados sensíveis',
      access_restricted: 'Acesso Restrito',
      no_permissions: 'Você não tem permissões para acessar este módulo',
      new_user: 'Novo Usuário',
      add_new_user: 'Adicionar Novo Usuário',
      full_name: 'Nome Completo',
      enter_name: 'Digite o nome completo',
      email: 'Email',
      enter_email: 'Digite o endereço de email',
      role: 'Função',
      password: 'Senha',
      enter_password: 'Digite a senha',
      user_created: 'Usuário Criado',
      user: 'Usuário',
      created_successfully: 'criado com sucesso',
      permission_updated: 'Permissão Atualizada',
      permission_updated_desc: 'A permissão foi atualizada',
      setting_updated: 'Configuração Atualizada',
      setting_updated_desc: 'A configuração foi atualizada',
      date_time: 'Data e Hora',
      action: 'Ação',
      resource: 'Recurso',
      status: 'Status',
      ip_address: 'Endereço IP',
    },
    permissions: {
      create_validations: 'Criar Validações',
      create_validations_desc: 'Criar novas validações',
      edit_validations: 'Editar Validações',
      edit_validations_desc: 'Editar validações existentes',
      manage_users: 'Gerenciar Usuários',
      manage_users_desc: 'Gerenciar usuários do sistema',
      export_reports: 'Exportar Relatórios',
      export_reports_desc: 'Exportar relatórios do sistema',
    },
    roles: {
      administrator: 'Administrador',
      coordinator: 'Coordenador',
      analyst: 'Analista',
      viewer: 'Visualizador',
    },
    status: {
      success: 'Sucesso',
      failed: 'Falhou',
      warning: 'Aviso',
      validado: 'Validado',
      proximo: 'Próximo ao Vencimento',
      vencido: 'Vencido',
      revalidacion: 'Em Revalidação',
      en_validacion: 'Em Validação',
      por_revalidar: 'Para Revalidar',
      primera_revision: 'Primeira Revisão',
      segunda_revision: 'Segunda Revisão',
    },
  }
};

const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>((localStorage.getItem('language') as Language) || 'es');

  React.useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LanguageProvider, useLanguage };
